adapter-path: /Users/moslmn/projects/transcripts_generator/models/personas/87723a18-d80d-4990-811c-bc083e48d537/adapters
batch-size: 1
data: /Users/moslmn/projects/transcripts_generator/models/personas/87723a18-d80d-4990-811c-bc083e48d537/data
grad-accumulation-steps: 4
grad-checkpoint: true
iters: 450
learning-rate: 5.0e-05
lora-layers: 24
lora_parameters:
  dropout: 0.0
  rank: 16
  scale: 10.0
max-seq-length: 1024
model: mlx-community/Mistral-7B-Instruct-v0.3-4bit
steps-per-eval: 100
steps-per-report: 10
train: true
val-batches: 25
